version: '3.7'

services:

  node:
    image: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PACKAGES: "nano wget curl"
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
    networks:
      - nodeapp-network

  nginx:

    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node
    ports:
      - "4000:4000"
    networks:
      - nodeapp-network


networks:
  nodeapp-network:
    driver: bridge